### ISSUE TITLE
"Grapple tightrope" puzzle couldn't be completed

### ISSUE THREAD

**Issue by alexfaxe** [slashnhax/nano-dungeoneering#17]
Log:
https://hastebin.com/ulucoxecun.css

Bot just stood next to the anvil not doing anything, I gave it a few minutes to see if it would have worked it out but it looked like it wouldn't.

I paused the bot and fixed it myself. After that everything worked out as it should have.

**Comment by alexfaxe** [comment]
#11

**Comment by slashnhax** [comment]
I can confirm it is fixed, but atm traversal through that room isn't complete ("walk-on tightrope")
